# Generated by Django 2.2 on 2020-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Другое'), ('food', 'Еда'), ('drink', 'Вода'), ('cloth', 'Одежда'), ('electronics', 'Электроника')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
